export enum ErrorCode {
    NotFound = "not_found",
    Unauthorized = "unauthorized",
    Forbidden = "forbidden",
    UnhandledError = "unhandled_error",
    ExternalError = "external_error",
    ValidationError = "validation_error",
    ProductNotFound = "product_not_found",
    LoginFailed = "login_failed",
    ProxyError = "proxy_error",
    NetworkError = "network_error",
    InvalidParams = "invalid_params",
    CanceledRequest = "canceled_request",
    BadRequest = "bad_request",
    EmailInUse = "auth/email-already-in-use",
    InvalidEmail = "auth/invalid-email",
    InvalidPassword = "auth/wrong-password",
    UserDoesNotExists = "auth/user-not-found",
    PopupClosed = "auth/popup-closed-by-user",
    UsernameExists = "auth/username-exists",
    EmailExists = "EMAIL_EXISTS",

    // Form
    FormLoginEmpty = "form/login-empty",
    FormEmailEmpty = "form/email-empty",
    FormUsernameEmpty = "form/username-empty",
    FormInvalidEmail = "form/invalid-email",
    PasswordsNotMatch = "form/passwords-not-match",
}
